### ISSUE TITLE
Dynamic schema removes indexes for Entity fields

### ISSUE THREAD

**Issue by bgold0** [tomwalder/php-gds#10]
I'm not sure if I am doing this the right way or not (or if it's just how Google works), but when I update a property, it turns off my Indexing for every other field as well.

    //$user_id is the id of the entry
    $obj_store = new GDS\Store($obj_gateway, "Users");
    $grab_user = $obj_store->fetchById($user_id);
    $obj_store->upsert($grab_user);

Do I need to add an `$obj_schema` again instead of `"Users"` in `$obj_store`?

**Comment by tomwalder** [comment]
As you have guessed - because you set up the Store object without a schema, it has used a "dynamic schema" - which has indexing turned off by default for all fields.

I suggest you use some sort of "Store Factory" to ensure that your User store always uses the same schema.

I will also re-title and update this issue as an enhancement to do something about this... not sure what yet!

**Comment by bgold0** [comment]
Okay cool, I'll just do that. Thanks for the explanation!
