### ISSUE TITLE
creating an item with a certain ID?

### ISSUE THREAD

**Issue by tony2001** [tomwalder/php-gds#149]
I'd like to create an entity with certain ID.
In Python it's as easy as "Entity(id=123)", but I can't seem to find a way to do it in PHP GDS.
From what I see, entry ID is always autogenerated, is there a way to disable it and specify ID manually?

**Comment by tomwalder** [comment]
IIRC, this can be done in the following way:

```php
// Build a new entity, and set the "keyId"
$obj_book = new GDS\Entity();
$obj_book->title = 'Romeo and Juliet';
$obj_book->setKeyId('123');

// Write it to Datastore
$obj_store = new GDS\Store('Book');
$obj_store->upsert($obj_book);
```

However, beware that when defining your own IDs, the preference is to use *Key Names*. 

This is because the Google random (numeric) ID algorithm does not check for duplicates against any you manually upsert. Only those it has issued itself as part of automatic inserts.

See the blue note here:

https://cloud.google.com/datastore/docs/concepts/entities#datastore-incomplete-key-php

**Comment by tony2001** [comment]
Thanks a lot, that helped.
