### ISSUE TITLE
Could you explain beginTransaction()?

### ISSUE THREAD

**Issue by bgold0** [tomwalder/php-gds#16]
If you get a second, I'd love to understand more about what `beginTransaction()` does and the benefits of it.

So normally if I want to update something, I'd do something like this, but I never add the transaction:

    $obj_book = $obj_book_store->fetchOne("SELECT * FROM Book WHERE blah = '123'");
    $obj_book->reads = $obj_book->reads + 1;
    $obj_book_store->upsert($obj_book);

**Comment by tomwalder** [comment]
It's like transactions in a regular DB environment - it helps ensure data consistency.

Using your example, if 2 users "read the book" at the same time, they will both try and increment the reads count by 1.

So, our first AND second requests both do this:

```php
// load object, having reads of 123
// update object, settings reads = 123 + 1 = 124
```

So, even though we have 2 reads, only 1 gets incremented because the Datastore supports a "last read wins" model.

This might not seem too bad for increment read counts of a book - but if you are deducting money from a bank account or something equally important, it could be pretty severe.

So, by using transactions you can ensure that only ONE of the two updates attempted is successful - the other will have to try again, by which point the count will be 124 - meaning we add 1 and set it back as 125.

The only additional line you need to add with my library is the ```beginTransaction()```

BUT - you will then have to implement a try/catch/retry loop. 

In my next release I am planning to introduce some helper/utility classes for things like transactional counter incrementing - with built in retry.

**Comment by bgold0** [comment]
Oh awesome! Great explanation that makes a lot of sense; thank you for that. I will definitly implement this in some places. Looking forward to the next release.
