### ISSUE TITLE
Upsert of simple entities appears to create duplicates

### ISSUE THREAD

**Issue by jrgrafton** [tomwalder/php-gds#81]
Sample code:

  // Write it to Datastore
  $obj_store = new GDS\Store('Votes');
  $obj_store->upsert($obj_store->createEntity([
    'questionId' => 124,
    'vote' => true,
    'user' => 'jrgrafton@',
    'time' => new DateTime('-2 hours')
  ]));

Expected: one entity created in datastore "Votes".
Actual: multiple entities created: http://d.pr/i/1e4V2

**Comment by tomwalder** [comment]
Hi there,

The code sample should create just one Entity.

Is your page request being made twice? e.g. do you have a `.*` handler in your `app.yam` that is causing favicon requests to hit your code? Check the access logs?

Tom

**Comment by tomwalder** [comment]
Closing, but please re-open if needed

**Comment by martinojes** [comment]
I experienced the exact same problem, very frustrating. Then I found this issue report, and the problem was indeed the wildcard handler, just like Tom suggested. The "GET /favicon.ico" request that is automatically run by the browser, triggers the PHP script a second time, with no obvious output except from duplicates showing up in Datastore..!

What is important to notice here is that my app.yaml configuration originates from the ["Hello, World! in 5 minutes"](https://cloud.google.com/appengine/docs/php/) example from the Google Cloud Platform documentation, so it is very likely that others will find themselves scratching their heads because of this.

One possible solution, for anyone trying to fix this:
Add a specific rule for the favicon request in the app.yaml file, such as:
```
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
```
For more information, read the documentation: [Configuring with app.yaml](https://cloud.google.com/appengine/docs/php/config/appconfig)

Keep up the good work Tom!
